version: "3.8"

services:
  server:
    build:
      context: .
    ports:
      - "8080:80" # Portweiterleitung (lokaler Port: Port im Container)
    volumes:
      - ./src:/var/www/html # Verknüpfen eines lokalen Verzeichnisses mit einem Verzeichnis im Container
    depends_on:
      - db # Abhängigkeit vom Datenbankdienst
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=my-secret-pw
      - DB_DATABASE=users

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8081:80" # Portweiterleitung für phpMyAdmin
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=my-secret-pw
    depends_on:
      - db # Abhängigkeit vom Datenbankdienst

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: users
    ports:
      - "3308:3306" # Portweiterleitung für MySQL
    volumes:
      - db-data:/var/lib/mysql # Zuordnen eines Volumes zum Speichern von MySQL-Daten

volumes:
  db-data: # Definieren eines Volumes für Datenbankdaten
